name: COMP208
dependencies:
  - python=3.10
  - pip
  - flask
  - numpy
  - scikit-learn
  - pandas
  - matplotlib
  - flask-sqlalchemy
  - conda-forge::flask-mail
  - conda-forge::google-cloud-storage
  - conda-forge::openai
  - pymysql
  - openpyxl
  - seaborn
  - conda-forge::imbalanced-learn
  - xlrd
  - conda-forge::langdetect