name: COMP208
channels:
  - defaults
  - conda-forge
dependencies:
  - flask
  - flask-mail
  - flask-sqlalchemy
  - google-cloud-storage
  - imbalanced-learn
  - langdetect
  - matplotlib
  - numpy
  - openai
  - openpyxl
  - pandas=1.5
  - pingouin
  - pip
  - prettytable
  - pymysql
  - python=3.10
  - scikit-learn
  - seaborn
  - statsmodels
  - xlrd
  - pip: # pip packages
      - better-profanity
      - psython
