name: COMP208
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.10  ## specify desired version
  - pip
  - tensorflow-deps
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision

  ## uncomment for use with Jupyter
  ## - ipykernel

  ## PyPI packages
  - pip:
      - tensorflow-macos
      - tensorflow-metal  ## optional, but recommended