name: ReleaseBot

on:
  # trigger deployment on every push to main branch
  push:
    branches: [release]
  # trigger deployment manually
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          prerelease: true
          bump-minor-pre-major: true